apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: machinedeployment
spec:
  background: false
  rules:
  - name: machinedeployment-label
    match:
      resources:
        kinds:
        - cluster.x-k8s.io/v1alpha3/MachineDeployment
        - cluster.x-k8s.io/v1alpha4/MachineDeployment
    context:
    - name: releaseVersion
      apiCall:
        urlPath: "/apis/cluster.x-k8s.io/v1alpha3/namespaces/{{ request.object.metadata.namespace }}/clusters"
        jmesPath: "items[?metadata.name == '{{request.object.metadata.labels.\"cluster.x-k8s.io/cluster-name\"}}'].metadata.labels.\"release.giantswarm.io/version\" | [0]"
    preconditions:
      any:
      - key: "{{ releaseVersion }}"
        operator: Equals
        value: "20.0.0"
    mutate:
      patchStrategicMerge:
        metadata:
          labels:
            +(cluster.x-k8s.io/watch-filter): "capi"
            cluster.x-k8s.io/watch-filter: "capi"
