[[- with .Values.Installation.V1 ]]
[[- if .Proxy.Enabled ]]
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: inject-proxy-env
spec:
  rules:
    - name: inject-proxy-env
      match:
        resources:
          kinds:
            - Pod
      mutate:
        patchStrategicMerge:
          spec:
            containers:
              - (name): "*"
                env:
                  [[- if .Secret.Proxy.HTTP ]]
                  - name: HTTP_PROXY
                    value: [[ .Secret.Proxy.HTTP ]]
                  [[- end ]]
                  [[- if .Secret.Proxy.HTTPS ]]
                  - name: HTTPS_PROXY
                    value: [[ .Secret.Proxy.HTTPS ]]
                  [[- end ]]
                  [[- if .Proxy.NoProxy ]]
                  - name: NO_PROXY
                    value: [[ join "," .Proxy.NoProxy ]]
                  [[- end ]]
[[- end ]]
[[- end ]]
