apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: cluster
spec:
  background: false
  rules:
  - name: cluster-label
    match:
      resources:
        kinds:
        - cluster.x-k8s.io/v1alpha3/Cluster
    context:
    - name: release
      apiCall:
        urlPath: "/apis/release.giantswarm.io/v1alpha1/releases"
        jmesPath: "items[?metadata.name == 'v{{ `{{` }} request.object.metadata.labels.\"release.giantswarm.io/version\" {{ `}}` }}'] | [0]"
    preconditions:
      any:
      - key: "{{ `{{` }} request.object.metadata.labels.\"release.giantswarm.io/version\" {{ `}}` }}"
        operator: Equals
        value: "20.0.0"
    mutate:
      patchStrategicMerge:
        metadata:
          labels:
            +(cluster.x-k8s.io/watch-filter): "capi"
            cluster.x-k8s.io/watch-filter: "capi"
            +(cluster-apps-operator.giantswarm.io/version): "{{ `{{` }} release.spec.components | [?name == 'cluster-apps-operator'].version | [0]{{ `}}` }}"
            cluster-apps-operator.giantswarm.io/version: "{{ `{{` }} release.spec.components | [?name == 'cluster-apps-operator'].version | [0]{{ `}}` }}"
