apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: kubeadmcontrolplane
spec:
  rules:
  - name: kubeadmcontrolplane-defaults
    match:
      resources:
        kinds:
        - controlplane.cluster.x-k8s.io/v1alpha3/KubeadmControlPlane
    context:
    - name: releaseVersion
      apiCall:
        urlPath: "/apis/cluster.x-k8s.io/v1alpha3/namespaces/{{ `{{` }} request.object.metadata.namespace {{ `}}` }}/clusters"
        jmesPath: "items[?metadata.name == '{{ `{{` }}request.object.metadata.labels.\"cluster.x-k8s.io/cluster-name\"{{ `}}` }}'].metadata.labels.\"release.giantswarm.io/version\" | [0]"
    - name: release
      apiCall:
        urlPath: "/apis/release.giantswarm.io/v1alpha1/releases"
        jmesPath: "items[?metadata.name == 'v{{ `{{` }} releaseVersion {{ `}}` }}'] | [0]"
    mutate:
      patchStrategicMerge:
        metadata:
          labels:
            +(cluster.x-k8s.io/watch-filter): "{{ `{{` }} release.spec.components[] | [?name == 'cluster-api-control-plane'].version | [0]{{ `}}` }}"
            cluster.x-k8s.io/watch-filter: "{{ `{{` }} release.spec.components[] | [?name == 'cluster-api-control-plane'].version | [0]{{ `}}` }}"
        spec:
          kubeadmConfigSpec:
            clusterConfiguration:
              controllerManager:
                extraArgs:
                  bind-address: 0.0.0.0
              scheduler:
                extraArgs:
                  bind-address: 0.0.0.0
            initConfiguration:
              nodeRegistration:
                kubeletExtraArgs:
                  healthz-bind-address: 0.0.0.0
