{{- with .Values.Installation.V1.Secret.Proxy }}
{{- if .Enabled }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: inject-proxy-env
spec:
  rules:
    - name: inject-proxy-env
      match:
        resources:
          kinds:
            - Pod
      mutate:
        patchStrategicMerge:
          spec:
            containers:
              - (name): "*"
                env:
                  [[- if .Enabled ]]
                  - name: HTTP_PROXY
                    value: [[ .HTTP ]]
                  [[- end ]]
                  [[- if .HTTPS ]]
                  - name: HTTPS_PROXY
                    value: [[ .HTTPS ]]
                  [[- end ]]
                  [[- if .NoProxy ]]
                  - name: NO_PROXY
                    value: [[ join "," .NoProxy ]]
                  [[- end ]]
[[- end ]]
[[- end ]]
