
version: 2.1

orbs:
  architect: giantswarm/architect@4.2.0


jobs:
  verify:
    docker:
      - image: cimg/base:2021.07
    steps:
      - checkout
      - run:
          name: Install Make
          command: |
            sudo apt-get update && sudo apt-get install make
      - run:
          name: Make verify
          command: |
            make verify
  test-policies:
    machine: true
    environment:
      KIND_VERSION: v0.11.1
      KUBERNETES_VERSION: v1.21.1
    steps:
      - checkout
      - run:
          name: Download kind
          command: |
            curl -sLo kind https://github.com/kubernetes-sigs/kind/releases/download/$KIND_VERSION/kind-linux-amd64 && chmod +x kind && sudo mv kind /usr/bin
      - run:
          name: Download kubectl
          command: |
            curl -sLO https://storage.googleapis.com/kubernetes-release/release/$KUBERNETES_VERSION/bin/linux/amd64/kubectl && chmod +x kubectl  && sudo mv kubectl /usr/bin
      - run:
          name: Install Make
          command: |
            sudo apt-get update && sudo apt-get install make
      - run:
          name: Setup
          command: |
            make setup
      - architect/run-tests-with-abs:
          chart_dir: "./helm/policies-common"
          app-build-suite_version: "v0.2.3"
          app-build-suite_container_tag: "0.2.3"
          additional_app-build-suite_flags: "--external-cluster-version $KUBERNETES_VERSION"
      - architect/run-tests-with-abs:
          chart_dir: "./helm/policies-aws"
          app-build-suite_version: "v0.2.3"
          app-build-suite_container_tag: "0.2.3"
          additional_app-build-suite_flags: "--external-cluster-version $KUBERNETES_VERSION"
      - architect/run-tests-with-abs:
          chart_dir: "./helm/policies-azure"
          app-build-suite_version: "v0.2.3"
          app-build-suite_container_tag: "0.2.3"
          additional_app-build-suite_flags: "--external-cluster-version $KUBERNETES_VERSION"
      - architect/run-tests-with-abs:
          chart_dir: "./helm/policies-shared"
          app-build-suite_version: "v0.2.3"
          app-build-suite_container_tag: "0.2.3"
          additional_app-build-suite_flags: "--external-cluster-version $KUBERNETES_VERSION"
      - run:
          name: Export kind logs
          when: always
          command: |
            kind export logs --name kyverno-cluster logs
      - store_artifacts:
          path: logs

workflows:
  workflow:
    jobs:
      - verify:
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

      - test-policies:
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

      # Common
      - architect/push-to-app-catalog:
          name: push-policies-common-to-catalog
          app_catalog: control-plane-test-catalog
          app_catalog_test: control-plane-test-catalog
          attach_workspace: true
          chart: policies-common
          context: "architect"
          explicit_allow_chart_name_mismatch: true
          on_tag: false
          requires:
            - test-policies
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/
      # AWS
      - architect/push-to-app-catalog:
          name: push-policies-aws-to-catalog
          app_catalog: control-plane-test-catalog
          app_catalog_test: control-plane-test-catalog
          attach_workspace: true
          chart: policies-aws
          context: "architect"
          explicit_allow_chart_name_mismatch: true
          on_tag: false
          requires:
            - test-policies
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/
      # Azure
      - architect/push-to-app-catalog:
          name: push-policies-azure-to-catalog
          app_catalog: control-plane-test-catalog
          app_catalog_test: control-plane-test-catalog
          attach_workspace: true
          chart: policies-azure
          context: "architect"
          explicit_allow_chart_name_mismatch: true
          on_tag: false
          requires:
            - test-policies
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

      # Shared
      - architect/push-to-app-catalog:
          name: push-policies-shared-to-catalog
          app_catalog: control-plane-catalog
          app_catalog_test: control-plane-test-catalog
          attach_workspace: true
          chart: policies-shared
          context: "architect"
          explicit_allow_chart_name_mismatch: true
          requires:
            - test-policies
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: push-policies-shared-to-aws-app-collection
          context: architect
          app_name: "policies-shared"
          app_namespace: "giantswarm"
          app_collection_repo: "aws-app-collection"
          requires:
            - push-policies-shared-to-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: push-policies-shared-to-azure-app-collection
          context: architect
          app_name: "policies-shared"
          app_namespace: "giantswarm"
          app_collection_repo: "azure-app-collection"
          requires:
            - push-policies-shared-to-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: push-policies-shared-to-kvm-app-collection
          context: architect
          app_name: "policies-shared"
          app_namespace: "giantswarm"
          app_collection_repo: "kvm-app-collection"
          requires:
            - push-policies-shared-to-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
