
version: 2.1

orbs:
  architect: giantswarm/architect@2.5.0

workflows:
  workflow:
    jobs:
      # Common
      - architect/push-to-app-catalog:
          name: push-policies-common-to-catalog
          app_catalog: control-plane-test-catalog
          app_catalog_test: control-plane-test-catalog
          attach_workspace: true
          chart: policies-common
          context: "architect"
          explicit_allow_chart_name_mismatch: true
          on_tag: false
          skip_helm_chart_linting: true
      # KVM
      - architect/push-to-app-catalog:
          name: push-policies-kvm-to-catalog
          app_catalog: control-plane-test-catalog
          app_catalog_test: control-plane-test-catalog
          attach_workspace: true
          chart: policies-kvm
          context: "architect"
          explicit_allow_chart_name_mismatch: true
          on_tag: false
          skip_helm_chart_linting: true
          requires:
            - push-policies-common-to-catalog
      # AWS
      - architect/push-to-app-catalog:
          name: push-policies-aws-to-catalog
          app_catalog: control-plane-test-catalog
          app_catalog_test: control-plane-test-catalog
          attach_workspace: true
          chart: policies-aws
          context: "architect"
          explicit_allow_chart_name_mismatch: true
          on_tag: false
          skip_helm_chart_linting: true
          requires:
            - push-policies-kvm-to-catalog
      # Azure
      - architect/push-to-app-catalog:
          name: push-policies-azure-to-catalog
          app_catalog: control-plane-test-catalog
          app_catalog_test: control-plane-test-catalog
          attach_workspace: true
          chart: policies-azure
          context: "architect"
          explicit_allow_chart_name_mismatch: true
          on_tag: false
          skip_helm_chart_linting: true
          requires:
            - push-policies-aws-to-catalog
