
version: 2.1

orbs:
  architect: giantswarm/architect@2.7.0


jobs:
  test-policies:
    machine: true
    environment:
      KIND_VERSION: v0.10.0
      KUBERNETES_VERSION: v1.19.10
    steps:
      - checkout
      - run:
          name: Download kind
          command: |
            curl -sLo kind https://github.com/kubernetes-sigs/kind/releases/download/$KIND_VERSION/kind-linux-amd64
      - run:
          name: Download kubectl
          command: |
            curl -sLO https://storage.googleapis.com/kubernetes-release/release/$KUBERNETES_VERSION/bin/linux/amd64/kubectl && chmod +x kind kubectl
      - run:
          name: Create cluster
          command: |
            ./kind create cluster --image quay.io/giantswarm/kind-node:$KUBERNETES_VERSION --name apiextensions 2> /dev/null
      - run:
          name: Wait for the cluster node to be ready
          command: |
            ./kubectl wait nodes/apiextensions-control-plane --for=condition=ready --timeout=5m > /dev/null
      - run:
          name: Install Kyverno
          command: |
            ./kubectl create -f https://raw.githubusercontent.com/kyverno/kyverno/main/definitions/release/install.yaml > /dev/null
      - run:
          name: "Download dabs.sh script"
          command: |
            wget "https://raw.githubusercontent.com/giantswarm/app-build-suite/v0.2.2/dabs.sh"
            chmod +x dabs.sh
      - architect/run-tests-with-abs:
          chart_dir: "./helm/policies-common"
          app-build-suite_version: "v0.2.2"
          app-build-suite_container_tag: "0.2.2"
          additional_app-build-suite_flags: "--smoke-tests-cluster-type external --external-cluster-kubeconfig-path $KUBECONFIG --external-cluster-type kind --external-cluster-version $KUBERNETES_VERSION"


workflows:
  workflow:
    jobs:
      - test-policies

      # Common
      - architect/push-to-app-catalog:
          name: push-policies-common-to-catalog
          app_catalog: control-plane-test-catalog
          app_catalog_test: control-plane-test-catalog
          attach_workspace: true
          chart: policies-common
          context: "architect"
          explicit_allow_chart_name_mismatch: true
          on_tag: false
          skip_helm_chart_linting: true
          requires:
            - test-policies
      # KVM
      - architect/push-to-app-catalog:
          name: push-policies-kvm-to-catalog
          app_catalog: control-plane-test-catalog
          app_catalog_test: control-plane-test-catalog
          attach_workspace: true
          chart: policies-kvm
          context: "architect"
          explicit_allow_chart_name_mismatch: true
          on_tag: false
          skip_helm_chart_linting: true
          requires:
            - test-policies
      # AWS
      - architect/push-to-app-catalog:
          name: push-policies-aws-to-catalog
          app_catalog: control-plane-test-catalog
          app_catalog_test: control-plane-test-catalog
          attach_workspace: true
          chart: policies-aws
          context: "architect"
          explicit_allow_chart_name_mismatch: true
          on_tag: false
          skip_helm_chart_linting: true
          requires:
            - test-policies
      # Azure
      - architect/push-to-app-catalog:
          name: push-policies-azure-to-catalog
          app_catalog: control-plane-test-catalog
          app_catalog_test: control-plane-test-catalog
          attach_workspace: true
          chart: policies-azure
          context: "architect"
          explicit_allow_chart_name_mismatch: true
          on_tag: false
          skip_helm_chart_linting: true
          requires:
            - test-policies
