
version: 2.1

orbs:
  architect: giantswarm/architect@4.11.0

commands:
  run-ats:
    parameters:
      ats_version:
        type: string
        default: 0.1.4
      chart_archive_prefix:
        type: string
      tests_dir:
        type: string
    steps:
      - architect/run-tests-with-ats:
          chart_archive_prefix: "<< parameters.chart_archive_prefix >>"
          app-test-suite_version: "v<< parameters.ats_version >>"
          app-test-suite_container_tag: "<< parameters.ats_version >>"
          additional_app-test-suite_flags: "--external-cluster-version $KUBERNETES_VERSION --app-tests-pytest-tests-dir << parameters.tests_dir >>"

jobs:
  verify:
    docker:
      - image: cimg/base:2021.10
    steps:
      - checkout
      - run:
          name: Install Make
          command: |
            sudo apt-get update && sudo apt-get install make
      - run:
          name: Make verify
          command: |
            make verify

  validate:
    machine: true
    environment:
      KYVERNO_VERSION: v1.5.0-rc3
    steps:
      - checkout
      - run:
          name: Download kyverno cli
          command: |
            curl -sL https://github.com/kyverno/kyverno/releases/download/${KYVERNO_VERSION}/kyverno-cli_${KYVERNO_VERSION}_linux_x86_64.tar.gz | tar -xz -m kyverno && chmod +x kyverno && sudo mv kyverno /usr/bin
      - run:
          name: Validate policies
          command: |
            kyverno validate ./policies

  test-policies:
    machine: true
    environment:
      KIND_VERSION: v0.11.1
      KUBERNETES_VERSION: v1.21.1
      DABS_VERSION: v1.0.4
    steps:
      - checkout
      - run:
          name: Download kind
          command: |
            curl -sLo kind https://github.com/kubernetes-sigs/kind/releases/download/$KIND_VERSION/kind-linux-amd64 && chmod +x kind && sudo mv kind /usr/bin
      - run:
          name: Download kubectl
          command: |
            curl -sLO https://storage.googleapis.com/kubernetes-release/release/$KUBERNETES_VERSION/bin/linux/amd64/kubectl && chmod +x kubectl  && sudo mv kubectl /usr/bin
      - run:
          name: Download dabs.sh
          command: |
            wget -O dabs.sh https://github.com/giantswarm/app-build-suite/releases/download/$DABS_VERSION/dabs.sh && chmod +x dabs.sh && sudo mv dabs.sh /usr/bin
      - run:
          name: Install Make
          command: |
            sudo apt-get update && sudo apt-get install make
      - run:
          name: Install clusterctl
          command: |
            curl -L https://github.com/kubernetes-sigs/cluster-api/releases/download/v0.4.4/clusterctl-linux-amd64 -o clusterctl && chmod +x clusterctl  && sudo mv clusterctl /usr/bin
      - run:
          name: Create kind cluster and install kyverno
          command: |
            make kind-create kind-get-kubeconfig install-kyverno
      - run:
          name: Make chart archives
          command: |
            make dabs
      - run-ats:
          chart_archive_prefix: "policies-aws"
          tests_dir: "helm/policies-aws/tests/ats"
      - run-ats:
          chart_archive_prefix: "policies-azure"
          tests_dir: "helm/policies-azure/tests/ats"
      - run-ats:
          chart_archive_prefix: "policies-common"
          tests_dir: "helm/policies-common/tests/ats"
      - run-ats:
          chart_archive_prefix: "policies-openstack"
          tests_dir: "helm/policies-openstack/tests/ats"
      - run-ats:
          chart_archive_prefix: "policies-shared"
          tests_dir: "helm/policies-shared/tests/ats"
      - run-ats:
          chart_archive_prefix: "policies-vsphere"
          tests_dir: "helm/policies-vsphere/tests/ats"
      - run:
          name: Export kind logs
          when: always
          command: |
            kind export logs --name kyverno-cluster logs
      - store_artifacts:
          path: logs

workflows:
  workflow:
    jobs:
      - verify:
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

      - validate:
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

      - test-policies:
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

      # Common
      - architect/push-to-app-catalog:
          name: push-policies-common-to-catalog
          app_catalog: control-plane-catalog
          app_catalog_test: control-plane-test-catalog
          attach_workspace: true
          chart: policies-common
          context: "architect"
          explicit_allow_chart_name_mismatch: true
          on_tag: false
          requires:
            - test-policies
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/
      # AWS
      - architect/push-to-app-catalog:
          name: push-policies-aws-to-catalog
          app_catalog: control-plane-catalog
          app_catalog_test: control-plane-test-catalog
          attach_workspace: true
          chart: policies-aws
          context: "architect"
          explicit_allow_chart_name_mismatch: true
          on_tag: false
          requires:
            - test-policies
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/
      # Azure
      - architect/push-to-app-catalog:
          name: push-policies-azure-to-catalog
          app_catalog: control-plane-catalog
          app_catalog_test: control-plane-test-catalog
          attach_workspace: true
          chart: policies-azure
          context: "architect"
          explicit_allow_chart_name_mismatch: true
          on_tag: false
          requires:
            - test-policies
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/
      # Openstack
      - architect/push-to-app-catalog:
          name: push-policies-openstack-to-catalog
          app_catalog: control-plane-catalog
          app_catalog_test: control-plane-test-catalog
          attach_workspace: true
          chart: policies-openstack
          context: "architect"
          explicit_allow_chart_name_mismatch: true
          on_tag: false
          requires:
            - test-policies
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/
      # VSphere
      - architect/push-to-app-catalog:
          name: push-policies-vsphere-to-catalog
          app_catalog: control-plane-catalog
          app_catalog_test: control-plane-test-catalog
          attach_workspace: true
          chart: policies-vsphere
          context: "architect"
          explicit_allow_chart_name_mismatch: true
          on_tag: false
          requires:
            - test-policies
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

      # Shared
      - architect/push-to-app-catalog:
          name: push-policies-shared-to-catalog
          app_catalog: control-plane-catalog
          app_catalog_test: control-plane-test-catalog
          attach_workspace: true
          chart: policies-shared
          context: "architect"
          explicit_allow_chart_name_mismatch: true
          requires:
            - test-policies
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: push-policies-shared-to-aws-app-collection
          context: architect
          app_name: "policies-shared"
          app_namespace: "giantswarm"
          app_collection_repo: "aws-app-collection"
          requires:
            - push-policies-shared-to-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: push-policies-shared-to-azure-app-collection
          context: architect
          app_name: "policies-shared"
          app_namespace: "giantswarm"
          app_collection_repo: "azure-app-collection"
          requires:
            - push-policies-shared-to-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: push-policies-shared-to-kvm-app-collection
          context: architect
          app_name: "policies-shared"
          app_namespace: "giantswarm"
          app_collection_repo: "kvm-app-collection"
          requires:
            - push-policies-shared-to-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: push-policies-openstack-to-openstack-app-collection
          context: architect
          app_name: "policies-openstack"
          app_namespace: "giantswarm"
          app_collection_repo: "openstack-app-collection"
          requires:
            - push-policies-openstack-to-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: push-policies-shared-to-openstack-app-collection
          context: architect
          app_name: "policies-shared"
          app_namespace: "giantswarm"
          app_collection_repo: "openstack-app-collection"
          requires:
            - push-policies-shared-to-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
