apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: awsmachine-v20.0.1-v1alpha3
spec:
  rules:
  - name: awsmachine-label
    match:
      resources:
        kinds:
        - infrastructure.cluster.x-k8s.io/v1alpha3/AWSMachine
    context:
    - name: clusters
      apiCall:
<<<<<<< HEAD
        urlPath: "/apis/cluster.x-k8s.io/v1alpha3/namespaces/{{ request.object.metadata.namespace }}/clusters"
        jmesPath: "items[*]"
=======
        urlPath: "/apis/cluster.x-k8s.io/v1alpha3/namespaces/{{ request.object.metadata.namespace }}/clusters/{{ request.object.metadata.labels.\"cluster.x-k8s.io/cluster-name\" }}"
        jmesPath: "metadata.labels.\"release.giantswarm.io/version\""
>>>>>>> 042fb9144f93f96b150d3d76222f18a8b6267f3e
    - name: releases
      apiCall:
        urlPath: "/apis/release.giantswarm.io/v1alpha1/releases"
        jmesPath: "items[*]"
    preconditions:
    - key: "{{ clusterVersion }}"
      operator: Equals
      value: "20.0.1-v1alpha3"
    mutate:
      patchStrategicMerge:
        metadata:
          labels:
<<<<<<< HEAD
            +(cluster.x-k8s.io/watch-filter): "{{ releases[?metadata.name == 'v{{ clusters[?metadata.name == '{{ request.object.metadata.labels.\"cluster.x-k8s.io/cluster-name\" }}'].metadata.labels.\"release.giantswarm.io/version\" }}'].spec.components[] | [?name == 'cluster-api-provider-aws'].version | [0]}}"
            cluster.x-k8s.io/watch-filter: "{{ releases[?metadata.name == 'v{{ clusters[?metadata.name == '{{ request.object.metadata.labels.\"cluster.x-k8s.io/cluster-name\" }}'].metadata.labels.\"release.giantswarm.io/version\" }}'].spec.components[] | [?name == 'cluster-api-provider-aws'].version | [0]}}"
=======
            +(cluster.x-k8s.io/watch-filter): "{{ releases[?metadata.name == 'v20.0.1-v1alpha3'].spec.components[] | [?name == 'cluster-api-provider-aws'].version | [0]}}"
            cluster.x-k8s.io/watch-filter: "{{ releases[?metadata.name == 'v20.0.1-v1alpha3'].spec.components[] | [?name == 'cluster-api-provider-aws'].version | [0]}}"
>>>>>>> 042fb9144f93f96b150d3d76222f18a8b6267f3e
