apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: cluster
spec:
  rules:
  - name: cluster-label
    match:
      resources:
        kinds:
        - cluster.x-k8s.io/v1alpha3/Cluster
    context:
    - name: releases
      apiCall:
        urlPath: "/apis/release.giantswarm.io/v1alpha1/releases"
        jmesPath: "items[*]"
    mutate:
      overlay:
        metadata:
          labels:
            +(cluster.x-k8s.io/watch-filter): "{{ releases[?\"metadata.name\" == metadata.labels.\"release.giantswarm.io/version\"].spec.components[] | [?\"name\" == 'cluster-api-core'].version | [0]}}"
            cluster.x-k8s.io/watch-filter: "{{ releases[?\"metadata.name\" == metadata.labels.\"release.giantswarm.io/version\"].spec.components[] | [?\"name\" == 'cluster-api-core'].version | [0]}}"
