region: "eu-west-1"
sshKeyName: "ssh-key"

awsClusterRoleIdentity:
  roleARN: ""
  sourceIdentityRef:
    name: default
    kind: AWSClusterControllerIdentity

awsControlPlane:
  instanceType: t3.large
