apiVersion: v2
appVersion: v1.7.5
annotations:
  application.giantswarm.io/team: shield
  config.giantswarm.io/version: 1.x.x
dependencies:
  - name: kyverno-policies
    version: 3.2.0
description: |
  Kubernetes Pod Security Standards implemented as Kyverno policies
engine: gotpl
home: https://github.com/giantswarm/kyverno-policies
icon: https://s.giantswarm.io/app-icons/kyverno/1/light.svg
keywords:
  - kubernetes
  - policy agent
  - validating webhook
  - admissions controller
name: kyverno-policies
restrictions:
  clusterSingleton: true
sources:
  - https://github.com/giantswarm/kyverno-policies
version: 0.20.2
