kyverno-policies:
  podSecurityStandard: restricted
  includeOtherPolicies:
    - require-non-root-groups
  customLabels:
    application.giantswarm.io/team: shield

supplementalPolicies:
  policies:
    require-ro-rootfs:
      enabled: true
      mode: Audit
    restrict-external-ips:
      enabled: true
      mode: Audit
