kyverno-policies:
  podSecurityStandard: restricted
  customLabels:
    application.giantswarm.io/team: shield

supplementalPolicies:
  enabled: true
  policies:
    require-ro-rootfs:
      enabled: true
      mode: Audit
